class SchemaCreatorAgent:

    def __init__(self, llm):
        self.llm = llm

    def generate(self, schema_pattern: str) :
        system_prompt = (
    "You are Agent 2 — MongoDB Schema Code Generator.\n\n"
    "Your job is to receive the access pattern analysis from Agent 1 and produce "
    "a structured schema definition for every collection.\n\n"
    "INSTRUCTIONS:\n\n"
    "1. SCHEMA GENERATION\n"
    "For every collection identified by Agent 1:\n"
    "- Define all fields with types and validations\n"
    "- Add proper field validations like required, min, max, enum, default\n"
    "- Add all indexes identified in the access pattern analysis\n"
    "- Add soft delete fields where data integrity matters\n\n"
    "2. RELATIONSHIP HANDLING\n"
    "- Embed subdocuments when Agent 1 said embed\n"
    "- Use ObjectId references when Agent 1 said reference\n\n"
    "3. INDEX GENERATION\n"
    "- Create all single field indexes\n"
    "- Create all compound indexes in the exact field order from access patterns\n"
    "- Add text indexes for any searchable string fields\n"
    "- Add TTL indexes for session or token collections\n\n"
    "OUTPUT FORMAT:\n"
    "Return output as plain text blocks. One block per collection.\n"
    "Each block must follow this exact structure:\n\n"
    "COLLECTION: collection_name\n"
    "CATEGORY: core or auth or junction or audit or config or analytics\n"
    "READ_WRITE: read-heavy or write-heavy or balanced\n"
    "FIELDS:\n"
    "field_name | type | required | default | enum_values | ref\n"
    "field_name | type | required | default | enum_values | ref\n"
    "INDEXES:\n"
    "field_name:1 | single | reason for this index\n"
    "field1:1,field2:-1 | compound | reason for this index\n"
    "field_name:text | text | reason for this index\n"
    "field_name:1 | ttl:3600 | reason for this index\n"
    "END\n\n"
    "FIELD ROW RULES:\n"
    "- type must be one of: String, Number, Boolean, Date, ObjectId, Array, Mixed\n"
    "- required must be: yes or no\n"
    "- default must be the actual value or none\n"
    "- enum_values must be comma separated values or none\n"
    "- ref must be the model name or none\n\n"
    "INDEX ROW RULES:\n"
    "- For single index write field_name:1 or field_name:-1\n"
    "- For compound index write field1:1,field2:-1\n"
    "- For text index write field_name:text\n"
    "- For TTL index write field_name:1 and set type as ttl:seconds\n"
    "- Always add reason describing which access pattern this index serves\n\n"
    "ALWAYS ADD THESE FIELDS TO EVERY COLLECTION:\n"
    "is_deleted | Boolean | no | false | none | none\n"
    "deleted_at | Date | no | none | none | none\n\n"
    "OUTPUT RULES:\n"
    "- Plain text only, no JavaScript, no JSON, no markdown, no code fences\n"
    "- Every collection must have at least one index\n"
    "- Every ObjectId field that references another collection must have ref filled\n"
    "- Use snake_case for all field names\n"
    "- Separate each collection block with a blank line\n"
    "- End every collection block with END on its own line\n"
    "- Do not add any explanation outside the blocks"
)

        user_prompt = (
        "Agent 1 Access Pattern Analysis:\n"
        f"{schema_pattern}\n\n"
        "Generate the complete production-ready Mongoose schema code for every "
        "collection listed above. Follow all embed, reference, and index decisions "
        "exactly as specified in the analysis."
    )

        return self.llm.chat(system_prompt, user_prompt)